// This file is auto-generated by @hey-api/openapi-ts

export type AppointmentCreate = {
    patient_name: string;
    patient_email: string;
    reason_for_visit?: (string | null);
    doctor_id: string;
    availability_id: string;
};

export type AppointmentPublic = {
    patient_name: string;
    patient_email: string;
    reason_for_visit?: (string | null);
    id: string;
    doctor_id: string;
    availability_id: string;
    appointment_time: string;
    status: AppointmentStatus;
    created_at: string;
};

export type AppointmentsPublic = {
    data: Array<AppointmentPublic>;
    count: number;
};

export type AppointmentStatus = 'pending' | 'confirmed' | 'cancelled';

export type AppointmentUpdateStatus = {
    status: AppointmentStatus;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DoctorAvailabilitiesPublic = {
    data: Array<DoctorAvailabilityPublic>;
    count: number;
};

export type DoctorAvailabilityCreate = {
    start_time: string;
    end_time: string;
    doctor_id: string;
};

export type DoctorAvailabilityPublic = {
    start_time: string;
    end_time: string;
    id: string;
    doctor_id: string;
    is_booked: boolean;
};

export type DoctorCreate = {
    full_name: string;
    specialty: string;
    bio?: (string | null);
};

export type DoctorPublic = {
    full_name: string;
    specialty: string;
    bio?: (string | null);
    id: string;
};

export type DoctorsPublic = {
    data: Array<DoctorPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    role?: (UserRole | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'doctor' | 'patient';

export type UserRoleUpdate = {
    role: UserRole;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AppointmentsReadAppointmentsData = {
    doctorId?: (string | null);
    limit?: number;
    skip?: number;
    status?: (AppointmentStatus | null);
};

export type AppointmentsReadAppointmentsResponse = (AppointmentsPublic);

export type AppointmentsCreateAppointmentData = {
    requestBody: AppointmentCreate;
};

export type AppointmentsCreateAppointmentResponse = (AppointmentPublic);

export type AppointmentsReadAppointmentData = {
    appointmentId: string;
};

export type AppointmentsReadAppointmentResponse = (AppointmentPublic);

export type AppointmentsUpdateAppointmentStatusData = {
    appointmentId: string;
    requestBody: AppointmentUpdateStatus;
};

export type AppointmentsUpdateAppointmentStatusResponse = (AppointmentPublic);

export type DoctorsReadDoctorsData = {
    limit?: number;
    skip?: number;
};

export type DoctorsReadDoctorsResponse = (DoctorsPublic);

export type DoctorsCreateDoctorData = {
    requestBody: DoctorCreate;
};

export type DoctorsCreateDoctorResponse = (DoctorPublic);

export type DoctorsReadDoctorAvailabilitiesData = {
    doctorId: string;
    onlyOpen?: boolean;
};

export type DoctorsReadDoctorAvailabilitiesResponse = (DoctorAvailabilitiesPublic);

export type DoctorsCreateDoctorAvailabilityData = {
    requestBody: DoctorAvailabilityCreate;
};

export type DoctorsCreateDoctorAvailabilityResponse = (DoctorAvailabilityPublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UsersUpdateUserRoleData = {
    requestBody: UserRoleUpdate;
    userId: string;
};

export type UsersUpdateUserRoleResponse = (UserPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);