"""add user role field

Revision ID: 9652b0a32ff3
Revises: d3c4ab2301ab
Create Date: 2026-05-12 13:03:07.597758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9652b0a32ff3'
down_revision = 'd3c4ab2301ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM('doctor', 'patient', name='userrole', create_type=False)
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', role_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
