"""add_doctor_appointment_models

Revision ID: d3c4ab2301ab
Revises: 1a31ce608336
Create Date: 2026-05-12 12:07:17.615139

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'd3c4ab2301ab'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    appointment_status = postgresql.ENUM(
        "pending",
        "confirmed",
        "cancelled",
        name="appointmentstatus",
        create_type=False,
    )
    appointment_status.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "doctor",
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("specialty", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "doctoravailability",
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("doctor_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("is_booked", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "appointment",
        sa.Column("patient_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("patient_email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("reason_for_visit", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("doctor_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("availability_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("appointment_time", sa.DateTime(), nullable=False),
        sa.Column("status", appointment_status, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["availability_id"], ["doctoravailability.id"]),
        sa.ForeignKeyConstraint(["doctor_id"], ["doctor.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_appointment_availability_id"),
        "appointment",
        ["availability_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_appointment_availability_id"), table_name="appointment")
    op.drop_table("appointment")
    op.drop_table("doctoravailability")
    op.drop_table("doctor")
    postgresql.ENUM(name="appointmentstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
